### ISSUE TITLE
Broken unicode handling?

### ISSUE THREAD

**Issue by geon** [lemtzas/r-gamedev-screenshot-saturday#1]
An aggregator and viewer for /r/gamedevâ€™s Screenshot Saturday.

â€™ should be an '.

http://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC%E2%84%A2-showing-on-page-instead-of

**Comment by lemtzas** [comment]
Figured out what it was. Apparently nginx was not sending an encoding, so the defaults for some browsers displayed wonky while others displayed fine.

Should be fixed now.
