### ISSUE TITLE
Has stopped working

### ISSUE THREAD

**Issue by megan-rm** [lemtzas/r-gamedev-screenshot-saturday#3]
Since week 248, SSS Viewer hasn't updated or refreshed; only thumbnail is to https://www.reddit.com/r/gamedev/comments/3qxby7/-/cwj50e9

**Comment by lemtzas** [comment]
Thanks for the report!

It appears to have been due to a ruby segfault (wtf??) and has fixed itself for reasons unknown to me.

I'm going to do some more poking about to see if I can't figure out why and make sure it doesn't happen again.
